"""init

Revision ID: 442b5b3fe948
Revises:
Create Date: 2026-05-27 21:39:16.927939
"""
import sqlalchemy as sa
from alembic import op

revision = '442b5b3fe948'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sys_dept',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=False),
    sa.Column('updated_time', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['sys_dept.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_sys_dept_created_time'), 'sys_dept', ['created_time'], unique=False)
    op.create_index(op.f('ix_sys_dept_deleted_time'), 'sys_dept', ['deleted_time'], unique=False)
    op.create_index(op.f('ix_sys_dept_id'), 'sys_dept', ['id'], unique=False)
    op.create_index(op.f('ix_sys_dept_is_deleted'), 'sys_dept', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_sys_dept_parent_id'), 'sys_dept', ['parent_id'], unique=False)
    op.create_index(op.f('ix_sys_dept_status'), 'sys_dept', ['status'], unique=False)
    op.create_index(op.f('ix_sys_dept_updated_time'), 'sys_dept', ['updated_time'], unique=False)
    op.create_index(op.f('ix_sys_dept_uuid'), 'sys_dept', ['uuid'], unique=True)
    op.create_table('sys_dict_type',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('dict_type', sa.String(length=64), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=False),
    sa.Column('updated_time', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dict_type')
    )
    op.create_index(op.f('ix_sys_dict_type_created_time'), 'sys_dict_type', ['created_time'], unique=False)
    op.create_index(op.f('ix_sys_dict_type_deleted_time'), 'sys_dict_type', ['deleted_time'], unique=False)
    op.create_index(op.f('ix_sys_dict_type_id'), 'sys_dict_type', ['id'], unique=False)
    op.create_index(op.f('ix_sys_dict_type_is_deleted'), 'sys_dict_type', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_sys_dict_type_status'), 'sys_dict_type', ['status'], unique=False)
    op.create_index(op.f('ix_sys_dict_type_updated_time'), 'sys_dict_type', ['updated_time'], unique=False)
    op.create_index(op.f('ix_sys_dict_type_uuid'), 'sys_dict_type', ['uuid'], unique=True)
    op.create_table('sys_menu',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('permission', sa.String(length=100), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('route_name', sa.String(length=100), nullable=True),
    sa.Column('route_path', sa.String(length=200), nullable=True),
    sa.Column('component_path', sa.String(length=200), nullable=True),
    sa.Column('redirect', sa.String(length=200), nullable=True),
    sa.Column('hidden', sa.Boolean(), nullable=False),
    sa.Column('keep_alive', sa.Boolean(), nullable=False),
    sa.Column('always_show', sa.Boolean(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('affix', sa.Boolean(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=False),
    sa.Column('updated_time', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['sys_menu.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sys_menu_created_time'), 'sys_menu', ['created_time'], unique=False)
    op.create_index(op.f('ix_sys_menu_deleted_time'), 'sys_menu', ['deleted_time'], unique=False)
    op.create_index(op.f('ix_sys_menu_id'), 'sys_menu', ['id'], unique=False)
    op.create_index(op.f('ix_sys_menu_is_deleted'), 'sys_menu', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_sys_menu_parent_id'), 'sys_menu', ['parent_id'], unique=False)
    op.create_index(op.f('ix_sys_menu_status'), 'sys_menu', ['status'], unique=False)
    op.create_index(op.f('ix_sys_menu_updated_time'), 'sys_menu', ['updated_time'], unique=False)
    op.create_index(op.f('ix_sys_menu_uuid'), 'sys_menu', ['uuid'], unique=True)
    op.create_table('sys_param',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=False),
    sa.Column('updated_time', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_index(op.f('ix_sys_param_created_time'), 'sys_param', ['created_time'], unique=False)
    op.create_index(op.f('ix_sys_param_deleted_time'), 'sys_param', ['deleted_time'], unique=False)
    op.create_index(op.f('ix_sys_param_id'), 'sys_param', ['id'], unique=False)
    op.create_index(op.f('ix_sys_param_is_deleted'), 'sys_param', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_sys_param_status'), 'sys_param', ['status'], unique=False)
    op.create_index(op.f('ix_sys_param_updated_time'), 'sys_param', ['updated_time'], unique=False)
    op.create_index(op.f('ix_sys_param_uuid'), 'sys_param', ['uuid'], unique=True)
    op.create_table('sys_position',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=False),
    sa.Column('updated_time', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_sys_position_created_time'), 'sys_position', ['created_time'], unique=False)
    op.create_index(op.f('ix_sys_position_deleted_time'), 'sys_position', ['deleted_time'], unique=False)
    op.create_index(op.f('ix_sys_position_id'), 'sys_position', ['id'], unique=False)
    op.create_index(op.f('ix_sys_position_is_deleted'), 'sys_position', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_sys_position_status'), 'sys_position', ['status'], unique=False)
    op.create_index(op.f('ix_sys_position_updated_time'), 'sys_position', ['updated_time'], unique=False)
    op.create_index(op.f('ix_sys_position_uuid'), 'sys_position', ['uuid'], unique=True)
    op.create_table('sys_role',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('data_scope', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=False),
    sa.Column('updated_time', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_sys_role_created_time'), 'sys_role', ['created_time'], unique=False)
    op.create_index(op.f('ix_sys_role_deleted_time'), 'sys_role', ['deleted_time'], unique=False)
    op.create_index(op.f('ix_sys_role_id'), 'sys_role', ['id'], unique=False)
    op.create_index(op.f('ix_sys_role_is_deleted'), 'sys_role', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_sys_role_status'), 'sys_role', ['status'], unique=False)
    op.create_index(op.f('ix_sys_role_updated_time'), 'sys_role', ['updated_time'], unique=False)
    op.create_index(op.f('ix_sys_role_uuid'), 'sys_role', ['uuid'], unique=True)
    op.create_table('sys_dict_data',
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('value', sa.String(length=64), nullable=False),
    sa.Column('dict_type', sa.String(length=64), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('dict_type_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=False),
    sa.Column('updated_time', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dict_type_id'], ['sys_dict_type.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sys_dict_data_created_time'), 'sys_dict_data', ['created_time'], unique=False)
    op.create_index(op.f('ix_sys_dict_data_deleted_time'), 'sys_dict_data', ['deleted_time'], unique=False)
    op.create_index(op.f('ix_sys_dict_data_dict_type'), 'sys_dict_data', ['dict_type'], unique=False)
    op.create_index(op.f('ix_sys_dict_data_id'), 'sys_dict_data', ['id'], unique=False)
    op.create_index(op.f('ix_sys_dict_data_is_deleted'), 'sys_dict_data', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_sys_dict_data_status'), 'sys_dict_data', ['status'], unique=False)
    op.create_index(op.f('ix_sys_dict_data_updated_time'), 'sys_dict_data', ['updated_time'], unique=False)
    op.create_index(op.f('ix_sys_dict_data_uuid'), 'sys_dict_data', ['uuid'], unique=True)
    op.create_table('sys_role_depts',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('dept_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dept_id'], ['sys_dept.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['sys_role.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'dept_id')
    )
    op.create_table('sys_role_menus',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('menu_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['menu_id'], ['sys_menu.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['sys_role.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'menu_id')
    )
    op.create_table('sys_user',
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('mobile', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('gender', sa.String(length=1), nullable=True),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('dept_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=False),
    sa.Column('updated_time', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_time', sa.DateTime(), nullable=True),
    sa.Column('created_id', sa.Integer(), nullable=True),
    sa.Column('updated_id', sa.Integer(), nullable=True),
    sa.Column('deleted_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_id'], ['sys_user.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_id'], ['sys_user.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dept_id'], ['sys_dept.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_id'], ['sys_user.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('mobile'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_sys_user_created_id'), 'sys_user', ['created_id'], unique=False)
    op.create_index(op.f('ix_sys_user_created_time'), 'sys_user', ['created_time'], unique=False)
    op.create_index(op.f('ix_sys_user_deleted_id'), 'sys_user', ['deleted_id'], unique=False)
    op.create_index(op.f('ix_sys_user_deleted_time'), 'sys_user', ['deleted_time'], unique=False)
    op.create_index(op.f('ix_sys_user_dept_id'), 'sys_user', ['dept_id'], unique=False)
    op.create_index(op.f('ix_sys_user_id'), 'sys_user', ['id'], unique=False)
    op.create_index(op.f('ix_sys_user_is_deleted'), 'sys_user', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_sys_user_status'), 'sys_user', ['status'], unique=False)
    op.create_index(op.f('ix_sys_user_updated_id'), 'sys_user', ['updated_id'], unique=False)
    op.create_index(op.f('ix_sys_user_updated_time'), 'sys_user', ['updated_time'], unique=False)
    op.create_index(op.f('ix_sys_user_uuid'), 'sys_user', ['uuid'], unique=True)
    op.create_table('biz_student',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('student_no', sa.String(length=32), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=False),
    sa.Column('updated_time', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_time', sa.DateTime(), nullable=True),
    sa.Column('created_id', sa.Integer(), nullable=True),
    sa.Column('updated_id', sa.Integer(), nullable=True),
    sa.Column('deleted_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_id'], ['sys_user.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_id'], ['sys_user.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_id'], ['sys_user.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_biz_student_created_id'), 'biz_student', ['created_id'], unique=False)
    op.create_index(op.f('ix_biz_student_created_time'), 'biz_student', ['created_time'], unique=False)
    op.create_index(op.f('ix_biz_student_deleted_id'), 'biz_student', ['deleted_id'], unique=False)
    op.create_index(op.f('ix_biz_student_deleted_time'), 'biz_student', ['deleted_time'], unique=False)
    op.create_index(op.f('ix_biz_student_id'), 'biz_student', ['id'], unique=False)
    op.create_index(op.f('ix_biz_student_is_deleted'), 'biz_student', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_biz_student_status'), 'biz_student', ['status'], unique=False)
    op.create_index(op.f('ix_biz_student_student_no'), 'biz_student', ['student_no'], unique=True)
    op.create_index(op.f('ix_biz_student_updated_id'), 'biz_student', ['updated_id'], unique=False)
    op.create_index(op.f('ix_biz_student_updated_time'), 'biz_student', ['updated_time'], unique=False)
    op.create_index(op.f('ix_biz_student_uuid'), 'biz_student', ['uuid'], unique=True)
    op.create_table('sys_operation_log',
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('request_path', sa.String(length=255), nullable=False),
    sa.Column('request_method', sa.String(length=20), nullable=False),
    sa.Column('request_payload', sa.Text(), nullable=True),
    sa.Column('request_ip', sa.String(length=64), nullable=True),
    sa.Column('login_location', sa.String(length=128), nullable=True),
    sa.Column('request_os', sa.String(length=128), nullable=True),
    sa.Column('request_browser', sa.String(length=128), nullable=True),
    sa.Column('response_code', sa.Integer(), nullable=True),
    sa.Column('response_json', sa.Text(), nullable=True),
    sa.Column('process_time', sa.String(length=32), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=False),
    sa.Column('updated_time', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_time', sa.DateTime(), nullable=True),
    sa.Column('created_id', sa.Integer(), nullable=True),
    sa.Column('updated_id', sa.Integer(), nullable=True),
    sa.Column('deleted_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_id'], ['sys_user.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_id'], ['sys_user.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_id'], ['sys_user.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sys_operation_log_created_id'), 'sys_operation_log', ['created_id'], unique=False)
    op.create_index(op.f('ix_sys_operation_log_created_time'), 'sys_operation_log', ['created_time'], unique=False)
    op.create_index(op.f('ix_sys_operation_log_deleted_id'), 'sys_operation_log', ['deleted_id'], unique=False)
    op.create_index(op.f('ix_sys_operation_log_deleted_time'), 'sys_operation_log', ['deleted_time'], unique=False)
    op.create_index(op.f('ix_sys_operation_log_id'), 'sys_operation_log', ['id'], unique=False)
    op.create_index(op.f('ix_sys_operation_log_is_deleted'), 'sys_operation_log', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_sys_operation_log_status'), 'sys_operation_log', ['status'], unique=False)
    op.create_index(op.f('ix_sys_operation_log_updated_id'), 'sys_operation_log', ['updated_id'], unique=False)
    op.create_index(op.f('ix_sys_operation_log_updated_time'), 'sys_operation_log', ['updated_time'], unique=False)
    op.create_index(op.f('ix_sys_operation_log_uuid'), 'sys_operation_log', ['uuid'], unique=True)
    op.create_table('sys_user_positions',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['position_id'], ['sys_position.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['sys_user.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'position_id')
    )
    op.create_table('sys_user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['sys_role.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['sys_user.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sys_user_roles')
    op.drop_table('sys_user_positions')
    op.drop_index(op.f('ix_sys_operation_log_uuid'), table_name='sys_operation_log')
    op.drop_index(op.f('ix_sys_operation_log_updated_time'), table_name='sys_operation_log')
    op.drop_index(op.f('ix_sys_operation_log_updated_id'), table_name='sys_operation_log')
    op.drop_index(op.f('ix_sys_operation_log_status'), table_name='sys_operation_log')
    op.drop_index(op.f('ix_sys_operation_log_is_deleted'), table_name='sys_operation_log')
    op.drop_index(op.f('ix_sys_operation_log_id'), table_name='sys_operation_log')
    op.drop_index(op.f('ix_sys_operation_log_deleted_time'), table_name='sys_operation_log')
    op.drop_index(op.f('ix_sys_operation_log_deleted_id'), table_name='sys_operation_log')
    op.drop_index(op.f('ix_sys_operation_log_created_time'), table_name='sys_operation_log')
    op.drop_index(op.f('ix_sys_operation_log_created_id'), table_name='sys_operation_log')
    op.drop_table('sys_operation_log')
    op.drop_index(op.f('ix_biz_student_uuid'), table_name='biz_student')
    op.drop_index(op.f('ix_biz_student_updated_time'), table_name='biz_student')
    op.drop_index(op.f('ix_biz_student_updated_id'), table_name='biz_student')
    op.drop_index(op.f('ix_biz_student_student_no'), table_name='biz_student')
    op.drop_index(op.f('ix_biz_student_status'), table_name='biz_student')
    op.drop_index(op.f('ix_biz_student_is_deleted'), table_name='biz_student')
    op.drop_index(op.f('ix_biz_student_id'), table_name='biz_student')
    op.drop_index(op.f('ix_biz_student_deleted_time'), table_name='biz_student')
    op.drop_index(op.f('ix_biz_student_deleted_id'), table_name='biz_student')
    op.drop_index(op.f('ix_biz_student_created_time'), table_name='biz_student')
    op.drop_index(op.f('ix_biz_student_created_id'), table_name='biz_student')
    op.drop_table('biz_student')
    op.drop_index(op.f('ix_sys_user_uuid'), table_name='sys_user')
    op.drop_index(op.f('ix_sys_user_updated_time'), table_name='sys_user')
    op.drop_index(op.f('ix_sys_user_updated_id'), table_name='sys_user')
    op.drop_index(op.f('ix_sys_user_status'), table_name='sys_user')
    op.drop_index(op.f('ix_sys_user_is_deleted'), table_name='sys_user')
    op.drop_index(op.f('ix_sys_user_id'), table_name='sys_user')
    op.drop_index(op.f('ix_sys_user_dept_id'), table_name='sys_user')
    op.drop_index(op.f('ix_sys_user_deleted_time'), table_name='sys_user')
    op.drop_index(op.f('ix_sys_user_deleted_id'), table_name='sys_user')
    op.drop_index(op.f('ix_sys_user_created_time'), table_name='sys_user')
    op.drop_index(op.f('ix_sys_user_created_id'), table_name='sys_user')
    op.drop_table('sys_user')
    op.drop_table('sys_role_menus')
    op.drop_table('sys_role_depts')
    op.drop_index(op.f('ix_sys_dict_data_uuid'), table_name='sys_dict_data')
    op.drop_index(op.f('ix_sys_dict_data_updated_time'), table_name='sys_dict_data')
    op.drop_index(op.f('ix_sys_dict_data_status'), table_name='sys_dict_data')
    op.drop_index(op.f('ix_sys_dict_data_is_deleted'), table_name='sys_dict_data')
    op.drop_index(op.f('ix_sys_dict_data_id'), table_name='sys_dict_data')
    op.drop_index(op.f('ix_sys_dict_data_dict_type'), table_name='sys_dict_data')
    op.drop_index(op.f('ix_sys_dict_data_deleted_time'), table_name='sys_dict_data')
    op.drop_index(op.f('ix_sys_dict_data_created_time'), table_name='sys_dict_data')
    op.drop_table('sys_dict_data')
    op.drop_index(op.f('ix_sys_role_uuid'), table_name='sys_role')
    op.drop_index(op.f('ix_sys_role_updated_time'), table_name='sys_role')
    op.drop_index(op.f('ix_sys_role_status'), table_name='sys_role')
    op.drop_index(op.f('ix_sys_role_is_deleted'), table_name='sys_role')
    op.drop_index(op.f('ix_sys_role_id'), table_name='sys_role')
    op.drop_index(op.f('ix_sys_role_deleted_time'), table_name='sys_role')
    op.drop_index(op.f('ix_sys_role_created_time'), table_name='sys_role')
    op.drop_table('sys_role')
    op.drop_index(op.f('ix_sys_position_uuid'), table_name='sys_position')
    op.drop_index(op.f('ix_sys_position_updated_time'), table_name='sys_position')
    op.drop_index(op.f('ix_sys_position_status'), table_name='sys_position')
    op.drop_index(op.f('ix_sys_position_is_deleted'), table_name='sys_position')
    op.drop_index(op.f('ix_sys_position_id'), table_name='sys_position')
    op.drop_index(op.f('ix_sys_position_deleted_time'), table_name='sys_position')
    op.drop_index(op.f('ix_sys_position_created_time'), table_name='sys_position')
    op.drop_table('sys_position')
    op.drop_index(op.f('ix_sys_param_uuid'), table_name='sys_param')
    op.drop_index(op.f('ix_sys_param_updated_time'), table_name='sys_param')
    op.drop_index(op.f('ix_sys_param_status'), table_name='sys_param')
    op.drop_index(op.f('ix_sys_param_is_deleted'), table_name='sys_param')
    op.drop_index(op.f('ix_sys_param_id'), table_name='sys_param')
    op.drop_index(op.f('ix_sys_param_deleted_time'), table_name='sys_param')
    op.drop_index(op.f('ix_sys_param_created_time'), table_name='sys_param')
    op.drop_table('sys_param')
    op.drop_index(op.f('ix_sys_menu_uuid'), table_name='sys_menu')
    op.drop_index(op.f('ix_sys_menu_updated_time'), table_name='sys_menu')
    op.drop_index(op.f('ix_sys_menu_status'), table_name='sys_menu')
    op.drop_index(op.f('ix_sys_menu_parent_id'), table_name='sys_menu')
    op.drop_index(op.f('ix_sys_menu_is_deleted'), table_name='sys_menu')
    op.drop_index(op.f('ix_sys_menu_id'), table_name='sys_menu')
    op.drop_index(op.f('ix_sys_menu_deleted_time'), table_name='sys_menu')
    op.drop_index(op.f('ix_sys_menu_created_time'), table_name='sys_menu')
    op.drop_table('sys_menu')
    op.drop_index(op.f('ix_sys_dict_type_uuid'), table_name='sys_dict_type')
    op.drop_index(op.f('ix_sys_dict_type_updated_time'), table_name='sys_dict_type')
    op.drop_index(op.f('ix_sys_dict_type_status'), table_name='sys_dict_type')
    op.drop_index(op.f('ix_sys_dict_type_is_deleted'), table_name='sys_dict_type')
    op.drop_index(op.f('ix_sys_dict_type_id'), table_name='sys_dict_type')
    op.drop_index(op.f('ix_sys_dict_type_deleted_time'), table_name='sys_dict_type')
    op.drop_index(op.f('ix_sys_dict_type_created_time'), table_name='sys_dict_type')
    op.drop_table('sys_dict_type')
    op.drop_index(op.f('ix_sys_dept_uuid'), table_name='sys_dept')
    op.drop_index(op.f('ix_sys_dept_updated_time'), table_name='sys_dept')
    op.drop_index(op.f('ix_sys_dept_status'), table_name='sys_dept')
    op.drop_index(op.f('ix_sys_dept_parent_id'), table_name='sys_dept')
    op.drop_index(op.f('ix_sys_dept_is_deleted'), table_name='sys_dept')
    op.drop_index(op.f('ix_sys_dept_id'), table_name='sys_dept')
    op.drop_index(op.f('ix_sys_dept_deleted_time'), table_name='sys_dept')
    op.drop_index(op.f('ix_sys_dept_created_time'), table_name='sys_dept')
    op.drop_table('sys_dept')
    # ### end Alembic commands ###
